import { 
  Client, 
  Vendor,
  VendorRateHistory,
  Material, 
  MaterialInward, 
  Machine, 
  JobOrder, 
  JobFile, 
  QCCheck, 
  Dispatch, 
  Invoice, 
  Payment,
  UserProfile,
  CompanySettings
} from '@/types';

export const INITIAL_COMPANY_SETTINGS: CompanySettings = {
  company_name: 'The Wooden Art',
  logo_url: '',
  gstin: '27AAACP9988C1Z4',
  state_code: '27',
  state_name: 'Maharashtra',
  address: 'Plot 88, Sector 10, MIDC Industrial Area, Bhosari, Pune, MH - 411026',
  phone: '+91 20 2712 8899 / +91 98220 99887',
  email: 'operations@thewoodenart.com',
  bank_name: 'HDFC Bank Ltd',
  account_no: '50200049811204',
  account_type: 'Current Account',
  account_holder: 'The Wooden Art',
  ifsc_code: 'HDFC0000241',
  branch: 'MIDC Bhosari Pune Branch',
  payment_qr_url: '',
  payment_terms: [
    '100% payment is required before delivery. Delivery will be scheduled after payment confirmation.',
    'Goods once delivered will not be returned or exchanged, except in case of manufacturing defects.',
    'Please verify all order details before payment.',
  ],

  // Security & Passcode Defaults
  passcode_enabled: false,
  passcode_pin: '1234',
  auto_lock_timer: 0,

  // CNC Machine & Shop-Floor Defaults
  hourly_machining_rate: 850,
  shift_hours_per_day: 16,
  waste_margin_percent: 5,
  qr_auto_confirm: false,

  // Invoice Defaults
  invoice_prefix: 'TWA/INV/2026-27/',
  hsn_default: '4411',
  tax_mode: 'auto_gst',
};

export const INITIAL_USERS: UserProfile[] = [
  { id: 'usr-1', full_name: 'Vikramaditya Rao', email: 'admin@cncerp.com', role: 'admin', phone: '+91 98110 00111' },
  { id: 'usr-2', full_name: 'Suresh Patil', email: 'pm@cncerp.com', role: 'production_manager', phone: '+91 98220 22334' },
  { id: 'usr-3', full_name: 'Ramesh Pawar (VMC)', email: 'operator.vmc@cncerp.com', role: 'operator', phone: '+91 98330 44556' },
  { id: 'usr-4', full_name: 'Priya Kulkarni', email: 'accounts@cncerp.com', role: 'accounts', phone: '+91 98440 66778' },
  { id: 'usr-5', full_name: 'Mahesh Shinde', email: 'store@cncerp.com', role: 'store_clerk', phone: '+91 98550 88990' },
  { id: 'usr-6', full_name: 'Anand Deshmukh', email: 'qc@cncerp.com', role: 'qc_inspector', phone: '+91 98660 11223' },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'ven-1',
    vendor_name: 'Hindalco Metals & Alloys Ltd',
    gstin: '27AAACH8899A1Z1',
    category: 'raw_material',
    contact_person: 'Subhash Mehta',
    phone: '+91 98230 44112',
    email: 'sales@hindalco-dist.com',
    city: 'Pune',
    state_code: '27',
    address: 'Gate 4, Chakan Industrial Phase 1, Pune',
    outstanding_payable: 125000,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: 'ven-2',
    vendor_name: 'Apex Surface Heat Treaters',
    gstin: '27AABCA7766K1Z8',
    category: 'outsourced_process',
    contact_person: 'Sunil Jagtap',
    phone: '+91 94220 55331',
    email: 'heattreat@apexsurface.in',
    city: 'Bhosari Pune',
    state_code: '27',
    address: 'S-45, MIDC Bhosari, Pune',
    outstanding_payable: 34000,
    created_at: '2026-06-15T00:00:00Z',
  },
  {
    id: 'ven-3',
    vendor_name: 'Sandvik Coromant Tooling India',
    gstin: '27AAACS1122D1Z3',
    category: 'tooling',
    contact_person: 'Rahul Verma',
    phone: '+91 98900 88776',
    email: 'r.verma@sandvik.com',
    city: 'Pune',
    state_code: '27',
    address: 'Dapodi Industrial Zone, Pune',
    outstanding_payable: 18500,
    created_at: '2026-07-01T00:00:00Z',
  },
];

export const INITIAL_VENDOR_RATES: VendorRateHistory[] = [
  { id: 'rate-1', vendor_id: 'ven-1', vendor_name: 'Hindalco Metals & Alloys Ltd', material_name: 'Aluminium Block 6061-T6', rate_per_unit: 320, effective_date: '2026-07-01' },
  { id: 'rate-2', vendor_id: 'ven-1', vendor_name: 'Hindalco Metals & Alloys Ltd', material_name: 'Stainless Steel Round Bar 304', rate_per_unit: 280, effective_date: '2026-07-15' },
  { id: 'rate-3', vendor_id: 'ven-3', vendor_name: 'Sandvik Coromant Tooling India', material_name: 'Carbide Insert WNMG 080408', rate_per_unit: 450, effective_date: '2026-08-01' },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    company_name: 'Apex AeroTech Solutions Pvt Ltd',
    gstin: '27AAACA1234A1Z5',
    contact_person: 'Rajesh Sharma',
    phone: '+91 98220 11223',
    email: 'rajesh@apexaero.com',
    billing_address: 'Plot 42, MIDC Bhosari, Pune, MH - 411026',
    shipping_address: 'Plot 42, MIDC Bhosari, Pune, MH - 411026',
    city: 'Pune',
    state_code: '27',
    state_name: 'Maharashtra',
    credit_terms: '30 Days Net',
    payment_due_days: 30,
    credit_limit: 500000,
    status: 'active',
    outstanding_balance: 45000,
    created_at: '2026-07-10T10:00:00Z',
    contact_persons: [
      { id: 'cp-1', name: 'Rajesh Sharma', designation: 'Purchase Manager', phone: '+91 98220 11223', email: 'rajesh@apexaero.com' },
      { id: 'cp-2', name: 'Vikram Godbole', designation: 'Quality Head', phone: '+91 98220 11224', email: 'v.godbole@apexaero.com' },
    ],
  },
  {
    id: 'cli-2',
    company_name: 'Precision Hydro Dynamics',
    gstin: '27AABCP9876K1Z9',
    contact_person: 'Anita Kulkarni',
    phone: '+91 94231 55667',
    email: 'anita@precisionhydro.in',
    billing_address: 'Works 12, Chakan Industrial Area Phase 2, Pune, MH - 410501',
    shipping_address: 'Works 12, Chakan Industrial Area Phase 2, Pune, MH - 410501',
    city: 'Chakan',
    state_code: '27',
    state_name: 'Maharashtra',
    credit_terms: '15 Days Net',
    payment_due_days: 15,
    credit_limit: 250000,
    status: 'active',
    outstanding_balance: 12500,
    created_at: '2026-07-15T11:30:00Z',
    contact_persons: [
      { id: 'cp-3', name: 'Anita Kulkarni', designation: 'Director Procurement', phone: '+91 94231 55667', email: 'anita@precisionhydro.in' },
    ],
  },
  {
    id: 'cli-3',
    company_name: 'Gujarat Tooling Corp',
    gstin: '24AAACG4321B1Z2',
    contact_person: 'Vikram Patel',
    phone: '+91 98980 44332',
    email: 'v.patel@gujarattooling.com',
    billing_address: 'GIDC Industrial Estate, Vatva, Ahmedabad, GJ - 382445',
    shipping_address: 'GIDC Industrial Estate, Vatva, Ahmedabad, GJ - 382445',
    city: 'Ahmedabad',
    state_code: '24',
    state_name: 'Gujarat',
    credit_terms: 'Advance / 7 Days',
    payment_due_days: 7,
    credit_limit: 300000,
    status: 'active',
    outstanding_balance: 0,
    created_at: '2026-08-01T09:15:00Z',
    contact_persons: [
      { id: 'cp-4', name: 'Vikram Patel', designation: 'Plant Head', phone: '+91 98980 44332', email: 'v.patel@gujarattooling.com' },
    ],
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    name: 'HDMR MDF Sheet 18mm (8ft x 4ft)',
    category: 'MDF',
    grade: 'HDMR Exterior Grade',
    unit: 'sq_ft',
    hsn_code: '4411',
    thickness: 18,
    thickness_unit: 'mm',
    sheet_length: 8,
    sheet_width: 4,
    dimension_unit: 'ft',
    sqft_per_sheet: 32,
    current_stock: 640.0, // 20 sheets = 640 sq.ft
    reorder_level: 160.0,
    unit_cost: 85,
    batch_tracking_enabled: true,
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'mat-2',
    name: 'Corian Solid Surface Sheet 12mm (8ft x 4ft)',
    category: 'Corian',
    grade: 'Polymer Acrylic Solid Surface',
    unit: 'sq_ft',
    hsn_code: '3920',
    thickness: 12,
    thickness_unit: 'mm',
    sheet_length: 8,
    sheet_width: 4,
    dimension_unit: 'ft',
    sqft_per_sheet: 32,
    current_stock: 320.0, // 10 sheets = 320 sq.ft
    reorder_level: 96.0,
    unit_cost: 280,
    batch_tracking_enabled: true,
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'mat-3',
    name: 'Teak Wooden Plywood 19mm (8ft x 4ft)',
    category: 'Wooden',
    grade: 'BWP Grade 710',
    unit: 'sq_ft',
    hsn_code: '4412',
    thickness: 19,
    thickness_unit: 'mm',
    sheet_length: 8,
    sheet_width: 4,
    dimension_unit: 'ft',
    sqft_per_sheet: 32,
    current_stock: 128.0, // Low stock warning (4 sheets)
    reorder_level: 200.0,
    unit_cost: 135,
    batch_tracking_enabled: false,
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'mat-4',
    name: 'Mild Steel Sheet 2mm (8ft x 4ft)',
    category: 'MS',
    grade: 'CRCA IS 513',
    unit: 'kg',
    hsn_code: '7209',
    thickness: 2,
    thickness_unit: 'mm',
    sheet_length: 8,
    sheet_width: 4,
    dimension_unit: 'ft',
    sqft_per_sheet: 32,
    current_stock: 450.0,
    reorder_level: 100.0,
    unit_cost: 75,
    batch_tracking_enabled: true,
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'mat-5',
    name: 'Stainless Steel Sheet 304 3mm (8ft x 4ft)',
    category: 'SS',
    grade: 'SS304 2B Finish',
    unit: 'kg',
    hsn_code: '7219',
    thickness: 3,
    thickness_unit: 'mm',
    sheet_length: 8,
    sheet_width: 4,
    dimension_unit: 'ft',
    sqft_per_sheet: 32,
    current_stock: 220.0,
    reorder_level: 80.0,
    unit_cost: 280,
    batch_tracking_enabled: true,
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'mat-6',
    name: 'Cast Acrylic Sheet Clear 6mm (8ft x 4ft)',
    category: 'Acrylic',
    grade: 'High Clarity PMMA',
    unit: 'sq_ft',
    hsn_code: '3920',
    thickness: 6,
    thickness_unit: 'mm',
    sheet_length: 8,
    sheet_width: 4,
    dimension_unit: 'ft',
    sqft_per_sheet: 32,
    current_stock: 192.0,
    reorder_level: 64.0,
    unit_cost: 165,
    batch_tracking_enabled: true,
    created_at: '2026-07-01T00:00:00Z',
  },
];

export const INITIAL_MATERIAL_INWARD: MaterialInward[] = [
  {
    id: 'inw-1',
    ledger_type: 'grn_inward',
    material_id: 'mat-1',
    material_name: 'Aluminium Block 6061-T6',
    vendor_id: 'ven-1',
    vendor_name: 'Hindalco Metals & Alloys Ltd',
    client_id: null,
    client_name: null,
    source_type: 'own_stock',
    batch_no: 'BAT-ALU-2026-08',
    heat_no: 'HEAT-99421',
    dimensions: '150mm x 100mm x 500mm Block',
    qty: 200,
    unit_rate: 320,
    inward_date: '2026-08-01',
    challan_no: 'INV-ALU-9921',
    notes: 'Company own stock for stock valuation',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'inw-2',
    ledger_type: 'grn_inward',
    material_id: 'mat-2',
    material_name: 'Stainless Steel Round Bar 304',
    vendor_id: null,
    vendor_name: null,
    client_id: 'cli-1',
    client_name: 'Apex AeroTech Solutions Pvt Ltd',
    job_order_id: 'job-101',
    job_no: 'JOB-2026-001',
    source_type: 'client_supplied',
    batch_no: 'BAT-CLI-APEX-01',
    heat_no: 'HEAT-APEX-77',
    dimensions: 'Dia 50mm x 1200mm Bar (Client Free-Issue)',
    qty: 150,
    unit_rate: 0, // Client supplied
    inward_date: '2026-08-05',
    challan_no: 'APEX-DC-8041',
    notes: 'Free issue material provided by Apex AeroTech for Job work. Excluded from stock valuation.',
    created_at: '2026-08-05T14:20:00Z',
  },
];

export const INITIAL_MACHINES: Machine[] = [
  { id: 'mac-1', name: 'BFW VMC 850 (3-Axis)', code: 'VMC-01', machine_type: 'VMC 3-Axis', status: 'Active', hourly_rate: 1200, capacity_hours_per_day: 16 },
  { id: 'mac-2', name: 'Haas VF-4 SS (4-Axis)', code: 'VMC-02', machine_type: 'VMC 3-Axis', status: 'Active', hourly_rate: 1800, capacity_hours_per_day: 16 },
  { id: 'mac-3', name: 'Mazak QuickTurn 250 CNC Lathe', code: 'CNC-01', machine_type: 'CNC Lathe', status: 'Active', hourly_rate: 950, capacity_hours_per_day: 20 },
  { id: 'mac-4', name: 'Mitsubishi FA10S Wire EDM', code: 'EDM-01', machine_type: 'Wire EDM', status: 'Maintenance', hourly_rate: 1500, capacity_hours_per_day: 12 },
];

export const INITIAL_FILES: JobFile[] = [
  {
    id: 'file-1',
    job_order_id: 'job-101',
    client_id: 'cli-1',
    file_name: 'Hydraulic_Flange_Drawing_v2.pdf',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_type: 'pdf',
    version: 2,
    is_latest: true,
    approval_status: 'approved',
    uploaded_by_name: 'Suresh Patil',
    uploaded_at: '2026-08-05T11:00:00Z',
    comments: [
      { id: 'c-1', user_name: 'Suresh Patil', role: 'Production Manager', text: 'Approved revision v2 after verifying flange bolt circle radius.', created_at: '2026-08-05T11:30:00Z' },
    ],
  },
  {
    id: 'file-2',
    job_order_id: 'job-101',
    client_id: 'cli-1',
    file_name: 'Flange_3D_Model_RevB.dxf',
    file_url: 'https://example.com/files/Flange_3D_Model_RevB.dxf',
    file_type: 'cad',
    version: 1,
    is_latest: false,
    approval_status: 'superseded',
    uploaded_by_name: 'Suresh Patil',
    uploaded_at: '2026-08-05T11:05:00Z',
    comments: [],
  },
  {
    id: 'file-3',
    job_order_id: 'job-102',
    client_id: 'cli-2',
    file_name: 'Turbine_Housing_Photo.jpg',
    file_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    file_type: 'image',
    version: 1,
    is_latest: true,
    approval_status: 'approved',
    uploaded_by_name: 'Vikramaditya Rao',
    uploaded_at: '2026-08-08T16:30:00Z',
    comments: [],
  },
];

export const INITIAL_JOB_ORDERS: JobOrder[] = [
  {
    id: 'job-101',
    job_no: 'JOB-2026-001',
    po_ref: 'PO-APEX-9982',
    client_id: 'cli-1',
    client_name: 'Apex AeroTech Solutions Pvt Ltd',
    part_name: 'Hydraulic Aerospace Flange',
    part_number: 'AERO-FL-904',
    drawing_ref: 'DWG-904-REV2',
    drawing_version: 2,
    qty: 25,
    material_id: 'mat-2',
    material_name: 'Stainless Steel Round Bar 304',
    material_source: 'client_supplied',
    batch_no: 'BAT-CLI-APEX-01',
    heat_no: 'HEAT-APEX-77',
    machine_id: 'mac-1',
    machine_name: 'BFW VMC 850 (3-Axis)',
    operator_id: 'usr-3',
    operator_name: 'Ramesh Pawar (VMC)',
    status: 'Machining',
    priority: 'High',
    due_date: '2026-08-18',
    estimated_setup_min: 90,
    estimated_cycle_min: 45,
    actual_setup_min: 85,
    actual_cycle_min: 40,
    qr_code_token: 'QR-JOB-2026-001-AERO',
    notes: 'Tight tolerance ±0.015mm on bearing bore radius.',
    created_at: '2026-08-05T10:00:00Z',
    files: [INITIAL_FILES[0], INITIAL_FILES[1]],
    sub_ops: [
      { id: 'sub-1', op_sequence: 10, op_name: 'CNC Turning Roughing', machine_id: 'mac-3', machine_name: 'Mazak CNC Lathe', operator_name: 'Ramesh Pawar', estimated_min: 20, actual_min: 18, status: 'completed' },
      { id: 'sub-2', op_sequence: 20, op_name: 'VMC 3-Axis Milling', machine_id: 'mac-1', machine_name: 'BFW VMC 850', operator_name: 'Ramesh Pawar', estimated_min: 25, actual_min: 22, status: 'in_progress' },
    ],
    audit_logs: [
      { id: 'aud-1', stage: 'Order Received', user_name: 'Suresh Patil', timestamp: '2026-08-05T10:00:00Z', remarks: 'Job created against PO-APEX-9982' },
      { id: 'aud-2', stage: 'Material Allocated', user_name: 'Mahesh Shinde', timestamp: '2026-08-05T14:30:00Z', remarks: 'Allocated 150kg client SS304 bar' },
      { id: 'aud-3', stage: 'Programming', user_name: 'Suresh Patil', timestamp: '2026-08-06T09:00:00Z', remarks: 'CAM G-code program approved' },
      { id: 'aud-4', stage: 'Machining', user_name: 'Ramesh Pawar', timestamp: '2026-08-07T11:00:00Z', remarks: 'Setup on BFW VMC 850 started' },
    ],
  },
  {
    id: 'job-102',
    job_no: 'JOB-2026-002',
    po_ref: 'PO-HYDRO-4411',
    client_id: 'cli-2',
    client_name: 'Precision Hydro Dynamics',
    part_name: 'Piston Manifold Block',
    part_number: 'HYDRO-PMB-12',
    drawing_ref: 'DWG-PMB-12',
    drawing_version: 1,
    qty: 10,
    material_id: 'mat-1',
    material_name: 'Aluminium Block 6061-T6',
    material_source: 'own_stock',
    batch_no: 'BAT-ALU-2026-08',
    machine_id: 'mac-2',
    machine_name: 'Haas VF-4 SS (4-Axis)',
    operator_id: 'usr-3',
    operator_name: 'Ramesh Pawar (VMC)',
    status: 'Ready for Dispatch',
    priority: 'Medium',
    due_date: '2026-08-14',
    estimated_setup_min: 60,
    estimated_cycle_min: 25,
    actual_setup_min: 60,
    actual_cycle_min: 22,
    qr_code_token: 'QR-JOB-2026-002-HYDRO',
    notes: 'Anodizing completed. QC passed with zero defects.',
    created_at: '2026-08-08T09:00:00Z',
    files: [INITIAL_FILES[2]],
    sub_ops: [
      { id: 'sub-3', op_sequence: 10, op_name: 'Face Milling & Drilling', machine_id: 'mac-2', machine_name: 'Haas VF-4 SS', operator_name: 'Ramesh Pawar', estimated_min: 25, actual_min: 22, status: 'completed' },
    ],
    audit_logs: [
      { id: 'aud-5', stage: 'Order Received', user_name: 'Suresh Patil', timestamp: '2026-08-08T09:00:00Z' },
      { id: 'aud-6', stage: 'Machining', user_name: 'Ramesh Pawar', timestamp: '2026-08-09T10:00:00Z' },
      { id: 'aud-7', stage: 'Quality Check', user_name: 'Anand Deshmukh', timestamp: '2026-08-13T16:00:00Z', remarks: 'Passed 10/10 pcs' },
      { id: 'aud-8', stage: 'Ready for Dispatch', user_name: 'Anand Deshmukh', timestamp: '2026-08-14T09:00:00Z' },
    ],
  },
  {
    id: 'job-103',
    job_no: 'JOB-2026-003',
    po_ref: 'PO-GTC-7711',
    client_id: 'cli-3',
    client_name: 'Gujarat Tooling Corp',
    part_name: 'Shaft Adapter Bushing',
    part_number: 'GTC-BUSH-88',
    drawing_ref: 'DWG-BUSH-88',
    drawing_version: 1,
    qty: 50,
    material_id: 'mat-4',
    material_name: 'Brass Hex Rod C360',
    material_source: 'own_stock',
    batch_no: 'BAT-BRASS-09',
    machine_id: 'mac-3',
    machine_name: 'Mazak QuickTurn 250 CNC Lathe',
    operator_id: 'usr-3',
    operator_name: 'Ramesh Pawar (VMC)',
    status: 'Programming',
    priority: 'Urgent',
    due_date: '2026-08-20',
    estimated_setup_min: 45,
    estimated_cycle_min: 15,
    actual_setup_min: 0,
    actual_cycle_min: 0,
    qr_code_token: 'QR-JOB-2026-003-GTC',
    notes: 'Master program being finalized on Mastercam',
    created_at: '2026-08-12T14:00:00Z',
    files: [],
    sub_ops: [],
    audit_logs: [
      { id: 'aud-9', stage: 'Order Received', user_name: 'Suresh Patil', timestamp: '2026-08-12T14:00:00Z' },
      { id: 'aud-10', stage: 'Programming', user_name: 'Suresh Patil', timestamp: '2026-08-13T10:00:00Z' },
    ],
  },
];

export const INITIAL_QC_CHECKS: QCCheck[] = [
  {
    id: 'qc-1',
    job_order_id: 'job-102',
    job_no: 'JOB-2026-002',
    part_name: 'Piston Manifold Block',
    client_name: 'Precision Hydro Dynamics',
    inspector_name: 'Anand Deshmukh',
    inspected_qty: 10,
    passed_qty: 10,
    failed_qty: 0,
    result: 'pass',
    checklist_json: [
      { id: 'p-1', parameter: 'Outer Dimension (150mm)', expected: '150 ±0.05mm', actual: '150.02mm', passed: true },
      { id: 'p-2', parameter: 'Bore Diameter (45mm)', expected: '45.00 +0.02/-0.00mm', actual: '45.01mm', passed: true },
      { id: 'p-3', parameter: 'Surface Roughness (Ra)', expected: 'Ra 0.8', actual: 'Ra 0.6', passed: true },
    ],
    checked_at: '2026-08-13T16:00:00Z',
  },
];

export const INITIAL_DISPATCHES: Dispatch[] = [
  {
    id: 'dsp-1',
    challan_no: 'DC-2026-001',
    job_order_id: 'job-102',
    job_no: 'JOB-2026-002',
    client_id: 'cli-2',
    client_name: 'Precision Hydro Dynamics',
    part_name: 'Piston Manifold Block',
    dispatched_qty: 10,
    transporter: 'VRL Logistics',
    vehicle_no: 'MH 14 HG 4521',
    driver_phone: '+91 98221 00998',
    lr_no: 'VRL-PN-98211',
    eway_bill_no: '341098227651',
    dispatch_date: '2026-08-14',
    notes: 'Packed in wooden crate with anti-corrosion VCI bubble wrap.',
    created_at: '2026-08-14T11:00:00Z',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoice_no: 'INV-2627-001',
    financial_year: 'FY 2026-27',
    client_id: 'cli-1',
    client_name: 'Apex AeroTech Solutions Pvt Ltd',
    client_gstin: '27AAACA1234A1Z5',
    client_state_code: '27',
    job_order_id: 'job-101',
    job_no: 'JOB-2026-001',
    invoice_type: 'labour_only', // Client supplied material - no GST on material
    hsn_sac_code: '9988',
    labour_amount: 38135.59,
    material_amount: 0,
    subtotal: 38135.59,
    is_interstate: false,
    cgst_rate: 9,
    cgst_amount: 3432.20,
    sgst_rate: 9,
    sgst_amount: 3432.20,
    igst_rate: 0,
    igst_amount: 0,
    total_amount: 45000.00,
    paid_amount: 0,
    status: 'unpaid',
    invoice_date: '2026-08-10',
    due_date: '2026-09-09',
    created_at: '2026-08-10T15:00:00Z',
    items: [
      { id: 'ii-1', description: 'HDMR MDF 18mm CNC Router 2D Design Cutting Job', sqft: 32, rate: 85, amount: 2720, qty: 5, total: 13600 },
    ],
  },
  {
    id: 'inv-2',
    invoice_no: 'INV-2627-002',
    financial_year: 'FY 2026-27',
    client_id: 'cli-2',
    client_name: 'Precision Hydro Dynamics',
    client_gstin: '27AABCP9876K1Z9',
    client_state_code: '27',
    dispatch_id: 'dsp-1',
    job_order_id: 'job-102',
    job_no: 'JOB-2026-002',
    invoice_type: 'material_and_labour',
    hsn_sac_code: '8412',
    labour_amount: 15000,
    material_amount: 10000,
    subtotal: 25000,
    is_interstate: false,
    cgst_rate: 9,
    cgst_amount: 2250,
    sgst_rate: 9,
    sgst_amount: 2250,
    igst_rate: 0,
    igst_amount: 0,
    total_amount: 29500,
    paid_amount: 17000,
    status: 'partially_paid',
    invoice_date: '2026-08-14',
    due_date: '2026-08-29',
    created_at: '2026-08-14T12:00:00Z',
    items: [
      { id: 'ii-2', description: 'Acrylic 6mm Laser Engraving & Letter Cutting Work', sqft: 16, rate: 120, amount: 1920, qty: 3, total: 5760 },
    ],
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    invoice_id: 'inv-2',
    invoice_no: 'INV-2627-002',
    client_id: 'cli-2',
    client_name: 'Precision Hydro Dynamics',
    amount: 17000,
    mode: 'bank_transfer',
    reference_no: 'HDFCR52026081400912',
    paid_date: '2026-08-14',
    notes: 'Advance 50% + GST received via NEFT',
    created_at: '2026-08-14T12:30:00Z',
  },
];
